#
# Autogenerated by Thrift Compiler (0.8.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'arithmetic_types'

      module Tutorial
        module Arithmetic
          module Gen
    end
  end
end
